### ISSUE TITLE
Datalad setup with orphan branches fails to recursively push data

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/knowledge-base#2]
Origin: https://neurostars.org/t/datalad-setup-with-orphan-branches-fails-to-recursively-push-data/25372

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed (no response as of 2023-04-18)
- [ ] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by christian-monch** [comment]
OP seems to have declared this to be solved. I asked for confirmation

**Comment by christian-monch** [comment]
OP declared this as solved, closing it.
