### ISSUE TITLE
studyforrest/visualrois dataset has broken special remotes

### ISSUE THREAD

**Issue by bpoldrack** [psychoinformatics-de/knowledge-base#20]
Origin: https://github.com/psychoinformatics-de/studyforrest-data-visualrois/issues/6

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [ ] Fix the dataset and publish the fix
- [x] Write up how to fix this
- [ ] Inform OP about resolution

**Comment by bpoldrack** [comment]
The errors showing up for users are about several special remotes and their setup in this dataset.

1.) The most important issue is the original type git special remote `mddatasrc` pointing to the no longer existing `http://psydata.ovgu.de/studyforrest/visualrois/.git`. This needs to be changed to `https://datapub.fz-juelich.de/studyforrest/studyforrest/visualrois/.git`. This special remote has the UUID `9536f86d-eb34-42ed-8ffc-fafd63a2b87e`

2.) For some reason there's a second type git special remote registered under the same name `mddatasrc` but pointing to http://psydata.ovgu.de/studyforrest/freesurfer/.git. This appears to be a mistake to begin with. At the very least it should be changed to `autoenable=false` to avoid spamming users with misleading and irrelevant errors. I'd suggest to declare it dead in addition. This special remote has the UUID `db2e8480-0894-4e67-93b3-28d0d64d629b`.

3.) The ORA special remote pointing to INM-7 is not publicly available but autoenabled. Technically, that's fine and will report the inability to enable it during clone. The message is at INFO level, indicating its nothing to worry about. The message itself, however, is reporting an error. Especially when other errors occur this is misleading. I think it's worth considering to not autoenable it.


Fixing 1), is a bit non-obvious because of the git-type special remote and its interaction with an actual git remote.
Right after clone, one can not simply use `git annex enableremote mddatasrc location=NEWURL`, because git-annex would try to enable the git remote called `mddatasrc` that was added to `.git/config` during autoenabling of the git-type special remote. So, git-annex mistakes the name reference. If one uses the UUID instead, however, `git annex enableremote` will try to `git remote add` the respective git remote which already exists. Hence, this also fails. That's because `enableremote` does not seem to consider itself being possibly used for reconfiguration rather than plain enabling in its internal flow. It is however the way to reconfigure. Therefore, what is required is:

```
git remote remove mddatasrc
git annex enableremote 9536f86d-eb34-42ed-8ffc-fafd63a2b87e location=https://datapub.fz-juelich.de/studyforrest/studyforrest/visualrois/.git
```

The second call will then reintroduce the git remote with the corrected URL locally. In addition, I am not sure whether the "right" git remote would be there for everyone on every system at this point, because of the second `mddatasrc`. Removing any `mddatasrc` git remote from `.git/config` should work in any case, though.


WRT 2.) I'd suggest to 
```
git annex dead db2e8480-0894-4e67-93b3-28d0d64d629b
git remote remove mddatasrc
git annex enableremote db2e8480-0894-4e67-93b3-28d0d64d629b autoenable=false
git remote remove mddatasrc
```
Considering the fix for 1.) above, this is more convenient to do first. The `git remote remove` is done for the same reasons as in 1.)

WRT 3.):
This should be a matter of `git annex enableremote inm7-storage autoenable=false`, but I feel this needs judgement by others.

**Comment by adswa** [comment]
Here's a coordination issue for a collaborative fix: https://github.com/psychoinformatics-de/studyforrest-data/issues/62
