### ISSUE TITLE
Reliable way to add existing RIA as sibling after cloning from GitHub?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/knowledge-base#39]
Origin: [Neurostars](https://neurostars.org/t/reliable-way-to-add-existing-ria-as-sibling-after-cloning-from-github/25651), April 24th 2023

User asks how to reliably add RIA to all the subdatasets of a superdataset cloned from GitHub.

I replied with a proposed solution / explanations.

As always with workflow questions, I would appreciate someone else taking a look at my response.

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

Additional TODO:
- [x] Would be awesome if someone looked into the thread (especially my last message) and confirmed that I was right about `--existing reconfigure`
- [x] Do we need a knowledge base item? I think not, or a very short one.

**Comment by mih** [comment]
I read the thread and it is optimal given the current feature set. Thanks!

We need to improve the tooling, but we already have the respective issues.
