### ISSUE TITLE
Move a superdataset between different devices using `mv`.

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/knowledge-base#70]
OP asks whether is it save to move a superdataset via `mv` between different devices. I answered that it should be save if the file systems on the devices have identical capabilities, and the operating system's `mv` works reliably. I offered an alternative though, using `tar` to duplicate teh superdataset and check for its correctness before removing the old dataset.

I keep this issue open, because I wanted a second opinion before telling OP that it is safe to delete the original superdataset. And I  did not want to say: try it with `mv` and hope for the best.

Origin: Neurostars datalad tag: https://neurostars.org/t/moving-superdatasets-to-a-new-location/25797

TODO (not necessarily to be performed in this order)
- [X] Inform OP/Add reference to this issue at origin
- [X] Clarifying Qs asked or not needed
- [X] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by mih** [comment]
I posted a confirmation of @christian-monch 's assessment/recommendations.
