### ISSUE TITLE
Problems getting a subdataset from gitlab (redirect for credentials)

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/knowledge-base#71]
OP wants to clone from a gitlab instance. The server redirects to a sign-in page to receive credentials. No further help from my side (mentioned handbook section 1.3)

Origin: Stack overflow [datalad] <https://stackoverflow.com/questions/76219411/datalad-problems-getting-a-subdataset-from-gitlab-redirect-for-credentials>

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin (a posted answer was deleted, and I don't know whether an answer was received. I un-checked this task therefore)
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by christian-monch** [comment]
Ok, so obviously stack overflow has deleted my answer. I wrote:

> thank you for your question. I don't have an answer for you right away, but we will look into it. I assume you are aware of this section in the datalad handbook https://handbook.datalad.org/en/latest/beyond_basics/101-146-providers.html
>
> I have created a support issue in our knowledge base: https://github.com/psychoinformatics-de/knowledge-base/issues/71
> 
> A member of the datalad team should get back to you shortly.

Not sure what exactly triggered the deletion. According to stack overflow answers are deleted. Stack overflow describes their policies here: https://stackoverflow.com/help/deleted-answers

**Comment by loj** [comment]
No confirmation yet from OP if this solution fixes their problem. I will close this now, assuming that the available information is sufficient to resolve it. If that is not the case, or we get more information, this can be reopened.
