### ISSUE TITLE
Login keyring repeatedly prompts for password

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/knowledge-base#95]
Origin: GitHub: datalad/datalad issue #7444 (https://github.com/datalad/datalad/issues/7444)

A user is repeatedly presented with a password prompt for the keyring. Supposedly the correct keyring-password is not known.

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [ ] Nature of the issue is understood
- [x] Inform OP about resolution

**Comment by christian-monch** [comment]
Provided feedback to OP. I believe the nature of the problem is that the wrong password for access to the keyring-backend is entered. Referred OP to KBI0023

**Comment by adswa** [comment]
With @jsheunis we saw something on in the last office hour: He demo'ed attempts to addurl data from an access restricted dataverse. In the demo, he ran ``datalad credentials``, and after the first few credentials were displayed, something weird happened: he had to input the keyring password for every new displayed credential. It sounds similarish to the problem here. I've tried to reproduce it, but failed to far. @jsheunis could you share software versions and configurations on your system?

**Comment by jsheunis** [comment]
Sure:

- macOS Big Sur
- datalad v0.19.2
- datalad-next v1.0.0+ (current main)


<details>

<summary><b>datalad wtf</b></summary>

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/jsheunis/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/jsheunis/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/jsheunis/.local/share/python_keyring
## datalad
  - version: 0.19.2
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 17.04
  - cmd:annex: 10.20230227
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.31.1
  - cmd:ssh: 8.1p1
  - cmd:system-git: 2.31.1
  - cmd:system-ssh: 8.1p1
  - humanize: 4.4.0
  - iso8601: 1.1.0
  - keyring: 23.13.1
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.4
  - platformdirs: 2.6.2
  - requests: 2.28.2
## environment
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - LC_TERMINAL: iTerm2
  - LC_TERMINAL_VERSION: 3.4.5
  - PATH: /Users/jsheunis/.rbenv/shims:/Users/jsheunis/opt/miniconda3/envs/meow3/bin:/Users/jsheunis/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jsheunis/.dotfiles/bin:/usr/local/sbin:/usr/X11R6/bin:/usr/local/games:/usr/games
## extensions
  - catalog:
    - description: DataLad Catalog command suite
    - entrypoints:
      - datalad_catalog.add.Add:
        - class: Add
        - module: datalad_catalog.add
        - names:
          - catalog-add
          - catalog_add
      - datalad_catalog.catalog.Catalog:
        - class: Catalog
        - module: datalad_catalog.catalog
        - names:
          - catalog
          - catalog
      - datalad_catalog.create.Create:
        - class: Create
        - module: datalad_catalog.create
        - names:
          - catalog-create
          - catalog_create
      - datalad_catalog.get.Get:
        - class: Get
        - module: datalad_catalog.get
        - names:
          - catalog-get
          - catalog_get
      - datalad_catalog.serve.Serve:
        - class: Serve
        - module: datalad_catalog.serve
        - names:
          - catalog-serve
          - catalog_serve
      - datalad_catalog.set.Set:
        - class: Set
        - module: datalad_catalog.set
        - names:
          - catalog-set
          - catalog_set
      - datalad_catalog.translate.Translate:
        - class: Translate
        - module: datalad_catalog.translate
        - names:
          - catalog-translate
          - catalog_translate
      - datalad_catalog.validate.Validate:
        - class: Validate
        - module: datalad_catalog.validate
        - names:
          - catalog-validate
          - catalog_validate
    - module: datalad_catalog
    - version: v0.2.1b+14.g292624a.dirty
  - deprecated:
    - description: Deprecated functionality
    - entrypoints:
      - datalad_deprecated.annotate_paths.AnnotatePaths:
        - class: AnnotatePaths
        - module: datalad_deprecated.annotate_paths
        - names:
      - datalad_deprecated.ls.Ls:
        - class: Ls
        - module: datalad_deprecated.ls
        - names:
      - datalad_deprecated.metadata.aggregate.AggregateMetaData:
        - class: AggregateMetaData
        - module: datalad_deprecated.metadata.aggregate
        - names:
          - aggregate-metadata
          - aggregate_metadata
      - datalad_deprecated.metadata.extract_metadata.ExtractMetadata:
        - class: ExtractMetadata
        - module: datalad_deprecated.metadata.extract_metadata
        - names:
          - extract-metadata
          - extract_metadata
      - datalad_deprecated.metadata.metadata.Metadata:
        - class: Metadata
        - module: datalad_deprecated.metadata.metadata
        - names:
      - datalad_deprecated.metadata.search.Search:
        - class: Search
        - module: datalad_deprecated.metadata.search
        - names:
      - datalad_deprecated.publish.Publish:
        - class: Publish
        - module: datalad_deprecated.publish
        - names:
    - module: datalad_deprecated
    - version: 0.2.8
  - metalad:
    - description: DataLad semantic metadata command suite
    - entrypoints:
      - datalad_metalad.add.Add:
        - class: Add
        - module: datalad_metalad.add
        - names:
          - meta-add
          - meta_add
      - datalad_metalad.aggregate.Aggregate:
        - class: Aggregate
        - module: datalad_metalad.aggregate
        - names:
          - meta-aggregate
          - meta_aggregate
      - datalad_metalad.conduct.Conduct:
        - class: Conduct
        - module: datalad_metalad.conduct
        - names:
          - meta-conduct
          - meta_conduct
      - datalad_metalad.dump.Dump:
        - class: Dump
        - module: datalad_metalad.dump
        - names:
          - meta-dump
          - meta_dump
      - datalad_metalad.extract.Extract:
        - class: Extract
        - module: datalad_metalad.extract
        - names:
          - meta-extract
          - meta_extract
      - datalad_metalad.filter.Filter:
        - class: Filter
        - module: datalad_metalad.filter
        - names:
          - meta-filter
          - meta_filter
    - module: datalad_metalad
    - version: 0.4.12+108.g58318d5
  - neuroimaging:
    - description: Neuroimaging tools
    - entrypoints:
      - datalad_neuroimaging.bids2scidata.BIDS2Scidata:
        - class: BIDS2Scidata
        - module: datalad_neuroimaging.bids2scidata
        - names:
          - bids2scidata
    - module: datalad_neuroimaging
    - version: 0.3.3
  - next:
    - description: What is next in DataLad
    - entrypoints:
      - datalad_next.commands.create_sibling_webdav.CreateSiblingWebDAV:
        - class: CreateSiblingWebDAV
        - module: datalad_next.commands.create_sibling_webdav
        - names:
          - create-sibling-webdav
      - datalad_next.commands.credentials.Credentials:
        - class: Credentials
        - module: datalad_next.commands.credentials
        - names:
      - datalad_next.commands.download.Download:
        - class: Download
        - module: datalad_next.commands.download
        - names:
          - download
      - datalad_next.commands.ls_file_collection.LsFileCollection:
        - class: LsFileCollection
        - module: datalad_next.commands.ls_file_collection
        - names:
          - ls-file-collection
      - datalad_next.commands.tree.TreeCommand:
        - class: TreeCommand
        - module: datalad_next.commands.tree
        - names:
          - tree
    - module: datalad_next
    - version: 1.0.0b3+25.g0cb44b0
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.24
    - bloomfilter-2.0.1.0
    - cryptonite-0.30
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.4.4
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.1
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: darwin x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230227
## location
  - path: /Users/jsheunis
  - type: directory
## metadata.extractors
  - annex:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.annex
  - audio:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.audio
  - bids:
    - distribution: datalad-neuroimaging 0.3.3
    - module: datalad_neuroimaging.extractors.bids
  - bids_dataset:
    - distribution: datalad-neuroimaging 0.3.3
    - doc: Top level BIDS extractor class interfacing with metalad     Inherits from metalad's DatasetMetadataExtractor class
    - generation: 4
    - module: datalad_neuroimaging.extractors.bids_dataset
    - version: 0.0.1
  - datacite:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.datacite
  - datacite_gin:
    - distribution: datalad-catalog 0.2.1b0+5.gcae9a78.dirty
    - doc: Inherits from metalad's DatasetMetadataExtractor class
    - generation: 4
    - module: datalad_catalog.extractors.datacite_gin
    - version: 0.0.1
  - datalad_core:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.datalad_core
  - datalad_rfc822:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.datalad_rfc822
  - dicom:
    - distribution: datalad-neuroimaging 0.3.3
    - module: datalad_neuroimaging.extractors.dicom
  - exif:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.exif
  - external_dataset:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 4
    - module: datalad_metalad.extractors.external_dataset
  - external_file:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 4
    - module: datalad_metalad.extractors.external_file
  - frictionless_datapackage:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.frictionless_datapackage
  - image:
    - distribution: datalad-deprecated 0.2.8
    - module: datalad_deprecated.metadata.extractors.image
  - metalad_annex:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 3
    - module: datalad_metalad.extractors.annex
  - metalad_core:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 3
    - module: datalad_metalad.extractors.core
  - metalad_custom:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 3
    - module: datalad_metalad.extractors.custom
  - metalad_example_dataset:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 4
    - module: datalad_metalad.extractors.metalad_example_dataset
    - version: 0.0.1
  - metalad_example_file:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 4
    - module: datalad_metalad.extractors.metalad_example_file
    - version: 0.0.1
  - metalad_external_dataset:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 4
    - module: datalad_metalad.extractors.external_dataset
  - metalad_external_file:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 4
    - module: datalad_metalad.extractors.external_file
  - metalad_genericjson_dataset:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - doc: Generic JSON dataset-level extractor class     Inherits from metalad's DatasetMetadataExtractor class
    - generation: 4
    - module: datalad_metalad.extractors.genericjson_dataset
    - version: 0.0.1
  - metalad_genericjson_file:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - doc: Main 'custom' file-level extractor class     Inherits from metalad's FileMetadataExtractor class
    - generation: 4
    - module: datalad_metalad.extractors.genericjson_file
    - version: 0.0.1
  - metalad_runprov:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 3
    - module: datalad_metalad.extractors.runprov
  - metalad_studyminimeta:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - generation: 3
    - module: datalad_metalad.extractors.studyminimeta.main
  - nidm:
    - distribution: datalad-neuroimaging 0.3.3
    - module: datalad_neuroimaging.extractors.nidm
  - nifti1:
    - distribution: datalad-neuroimaging 0.3.3
    - module: datalad_neuroimaging.extractors.nifti1
  - xmp:
    - distribution: datalad-deprecated 0.2.8
    - load_error: ImportError(libxmp is not usable due to Exempi library not found.)
    - module: datalad_deprecated.metadata.extractors.xmp
## metadata.filters
  - metalad_demofilter:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - doc: Create a "histogram"-like summary of the key values of all specified name_tuple     across all metadata that is yielded by the metadata iterables.      Histograms bins are determined by the metadata format and "name" within the     format. The "name" is a flattened JSON key hierarchy.      The set of metadata yielded by the iterables is determined by the     metadata urls and the recursion flag that are passed to     "datalad meta-filter".
    - module: datalad_metalad.filters.demofilter
    - version: 1.0
## metadata.indexers
  - metalad_studyminimeta:
    - distribution: datalad-metalad 0.4.12+101.gd87bff8
    - doc: Indexer for metadata that was extracted from studyminimeta metadata (usually contained in ".studyminimeta.yaml"-files).
    - module: datalad_metalad.indexers.studyminimeta
## python
  - implementation: CPython
  - version: 3.10.9
## system
  - distribution: darwin/20.6.0 10.16/x86_64
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem:
    - CWD:
      - path: /Users/jsheunis
    - HOME:
      - path: /Users/jsheunis
    - TMP:
      - path: /var/folders/g7/720mm8ns7hg3d28_3yyzkx_r0000gp/T
  - max_path_length: 271
  - name: Darwin
  - release: 20.6.0
  - type: posix
  - version: Darwin Kernel Version 20.6.0: Thu Mar  9 20:39:26 PST 2023; root:xnu-7195.141.49.700.6~1/RELEASE_X86_64
```

</details>

I run `datalad credentials` and for each credential using the new credential system there's a new keychain prompt:

> python3 wants to use your confidential information stored in [credential-name] in your keychain

> The authenticity of "python3" cannot be verified. To allow this, enter the "login" keychain password

Selecting "always allow" makes that the prompts aren't shown again in the same session. But the prompt comes up again for every credential if I run the command after starting a new shell session.

**Comment by adswa** [comment]
Thanks for this infos! To you have datalad-next enabled?

**Comment by jsheunis** [comment]
🤭 🤦 

That fixed it lol

**Comment by adswa** [comment]
Upon re-reading the OP issue of this support event, I think loading and enabling datalad next can be of help there, too. I've have commented with this observation, and recommended to install and enable datalad-next

**Comment by christian-monch** [comment]
Will close this because OP's original problem is solved. The datalad-issue is still open though, because it highlights a problem in the datalad-core credential system (@adswa commented on that)
